HackYourFuture-CPH/fp-class22

packages/server/api/controllers/products.controller.js
packages/server/api/routes/index.js
packages/server/api/routes/products.router.js

feature(Get productById endpoint)

---

packages/client/src/components/ViewPageButton/ViewPageButton.component.js
packages/client/src/components/ViewPageButton/ViewPageButton.stories.js
packages/client/src/components/ViewPageButton/ViewPageButton.styles.css

feature(ProductDescription Button)

---

packages/client/src/components/ViewDropDown/ViewDropdown.component.js
packages/client/src/components/ViewDropDown/ViewDropdown.stories.js
packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css

feature(productdescription dropdown)

---

packages/client/src/App.js
packages/client/src/components/Product/ProductDescription/ProductDescription.styles.css
packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.component.js
packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.component.js
packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.component.js
packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
packages/client/src/components/ProductImage/ProductImage.component.js
packages/client/src/components/ProductImage/ProductImage.styles.css
packages/client/src/components/ViewDropDown/ViewDropdown.component.js
packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
packages/client/src/components/ViewPageButton/ViewPageButton.component.js
packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css
packages/client/src/containers/ProductView/ProductView.container.js
packages/client/src/containers/ProductView/ProductView.styles.css
packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.container.js
packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.styles.css
packages/client/src/containers/ProductView/index.js

Class22-33-product-view-page-styling-without-responsiveness

---

packages/client/src/App.js
packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js

feature(Collection Page): Add Collection page path and collection page

---

.vscode/settings.json

fix(boilerplate): typescript.validate.enable false

---

packages/client/src/components/ProductList/ProductList.component.css
packages/client/src/components/ProductList/ProductList.component.js
packages/client/src/components/ProductList/Products.js

It is about responsiveness on products collection  page
http://localhost:3000/collections
By changing width of screen

feature(ProductList layout responsveness)

---

packages/server/api/controllers/products.controller.js
packages/server/api/routes/products.router.js

It's about getting the products of particular category, created a getProductsByCategory function in products controller and changed swagger documentation  in products router.

feature(Get products By category endpoint)

---

packages/client/src/components/ProductList/ProductList.component.js

fix(ProductList): remove misplaced components

---

packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
packages/client/src/components/ProductImage/ProductImage.component.js
packages/client/src/components/ProductImage/ProductImage.styles.css
packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
packages/client/src/containers/ProductView/ProductView.container.js

This one is about responsiveness for mobile

feature(ProductView) with responsiveness

---

packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.js
packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.stories.js
packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.style.css
packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.js
packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.stories.js
packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.styles.css
packages/client/src/containers/ProductView/ProductViewCarousel/ProductViewCarousel.container.js

carousel for selecting back and forward pics by product category.

feature(carousel)components

---

packages/client/src/containers/ProductView/ProductView.container.js
packages/client/src/containers/ProductView/index.js
packages/client/src/containers/RelatedItems/RelatedItems.Container.js
packages/client/src/containers/RelatedItems/RelatedItems.styles.css

Created the Related Items Layout , done styling for the items and added this container in Product View Container

Class22 45 product view page related items layout

---

packages/server/api/controllers/categories.controller.js
packages/server/api/routes/categories.router.js
packages/server/api/routes/index.js

feature(categories endpoint):created get categories endpoint

---

packages/client/src/App.js
packages/client/src/components/Footer/Footer.component.js
packages/client/src/components/Footer/Footer.styles.css
packages/client/src/components/Navigation/Navigation.component.js
packages/client/src/containers/HomePage/HomePage.Container.js
packages/client/src/containers/HomePage/HomePage.styles.css
packages/client/src/containers/LandingPage/LandingPage.Container.js

Removing Navigation and Footer from pages and putting them in App.js
Adjusting the Footer styles so it sticks to the end - might need further adjustments.

refactor(App): centralise Navigation and Footer

---

packages/client/src/components/Cart/CartButtons/CartButtons.component.js
packages/client/src/components/Cart/CartContainer/CartContainer.component.js
packages/client/src/components/Cart/CartCount/CartCount.component.js
packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
packages/client/src/components/Cart/CartTable/CartTable.component.js
packages/client/src/components/Cart/CartTotal/CartTotal.component.js
packages/client/src/components/Cart/CartTotal/CartTotal.stories.js
packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js

styling were moved to other PR

CLASS22-58-cart-page-structure

---

packages/client/src/components/ProductCard/ProductCard.styles.css
packages/client/src/components/ProductList/ProductList.component.css
packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.style.css

Responsiveness of product crat compoents
[Please provide a short summary how your changes can be tested?](http://localhost:3000/collections)

Responsiveness of product card components

---

packages/client/src/components/Body/Body.component.js

Fix typo in the Button label: Show Now => Shop Now

fix(Body): fix typo in the Button label

---

packages/server/api/controllers/exampleResources.controller.js
packages/server/api/controllers/products.controller.js

featuer(Fix Typo Error):Fix Typo error in HttpError

---

packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
packages/client/src/components/ProductListDropDown/ProductListDropDown.style.css

feature(Remove Extra CSS file and Remove Media-queries)

---

packages/client/src/components/ProductCard/ProductCard.styles.css
packages/client/src/containers/ContactUs.styles.css

CLASS22-76-update-product-card-background-styling

---

packages/server/migrations/20221205212026_add_orders_table.js
packages/server/migrations/20221205220007_add_order_items_table.js
packages/server/seeds/development/v_orders.js
packages/server/seeds/development/w_orders_items.js

added migration of orders and order_item table

feature(migration): added migration of orders and order_items table

---

packages/server/migrations/20221205174532_reviews-table.js
packages/server/seeds/development/v-reviews.js

Class22 86 feature reviews add migrations and seeds

---

packages/client/src/App.js
packages/client/src/containers/FavoritesPage/FavoritesPage.container.js

Created Favirite page
[CLASS22-96]

feature(FavoritesPage): create favorites page

---

packages/client/src/components/Body/Body.component.js

Fix the button label to say Shop Now (instead of Show Now)

home-page-body-shop-now-button-typo-fix
